### ISSUE TITLE
Access using GITHUB_TOKEN?

### ISSUE THREAD

**Issue by stephendgilbert** [cs50/ddb50.vsix#11]
Hello.
I currently use the CS50 Dockerfile and .devcontainer, along with GitHub classroom for my classes (instead of cs50.dev). This has worked fine. Last summer, I had an issue, https://github.com/cs50/codespace/issues/78, which you fixed by explicitly checking for CS50_TOKEN and falling back on the GITHUB_TOKEN.
The recent addition of the AI model (explain code, rubber duck) has been a little frustrating, because they stopped working (except in cs50.dev). I have been sending students to the Web page (cs50.ai), but this is not as convenient as just using the menu commands inside VSCODE.
Would it be possible to make a similar modification in this case, that would allow the non-cs50.dev containers to work?
Thank you very much.

**Comment by rongxin-liu** [comment]
Thanks for letting us know. If you update your codespace now, it should works.
