### ISSUE TITLE
When chat transcript is cleared, can we retain the duck's default message up top, for consistency with cs50.ai?

### ISSUE THREAD

**Issue by dmalan** [cs50/ddb50.vsix#12]
**Before Clear**

<img width="304" alt="Screenshot 2023-09-17 at 10 54 35 AM" src="https://github.com/cs50/ddb50.vsix/assets/788678/0fbc42d2-2c4c-4a29-9e87-ae88e0056e79">

**After Clear**

<img width="299" alt="Screenshot 2023-09-17 at 10 55 18 AM" src="https://github.com/cs50/ddb50.vsix/assets/788678/f3ddccf2-907e-4f91-b06f-7ba2bf14e6e2">

**Comment by rongxin-liu** [comment]
https://github.com/cs50/ddb50.vsix/commit/8ea7025384f6e9b3d3a76dba001d59e379a09be3
