### ISSUE TITLE
Publish server code

### ISSUE THREAD

**Issue by bazylhorsey** [cs50/ddb50.vsix#15]
Would love to see the implementation of ddb as a service. There is a lot of knowledge to be gained in seeing behind the scenes of how the plugin was created and how chatgpt can be leveraged in an app.

**Comment by dmalan** [comment]
We'll likely hold an online workshop soon that goes into more detail!

**Comment by bazylhorsey** [comment]
Thanks @dmalan 
While I got your attention, huge fan of your work, I do problems from your courses as soon as they come out. Best lecture communication skills in the entire field.
I recommend your courses universally. 

_please, make a Rust course, perhaps specializing in OS or other systems_ ❤️
