### ISSUE TITLE
how do you actually open the duck?

### ISSUE THREAD

**Issue by CS50etudiant** [cs50/ddb50.vsix#4]
I have the extension, but I dont know how to activate it, I cant talk to the duck!!!

**Comment by rongxin-liu** [comment]
Please click on the duck debugger icon on the activity bar, then start chatting:
<img width="526" alt="Screen Shot 2022-07-29 at 08 48 46" src="https://user-images.githubusercontent.com/10591665/181763900-c9660a6d-95bd-4fe7-9211-74a93daa7891.png">
